# roles/el7/tasks/admin.yml
#
# Settings regarding the admin user
---
- name: Make sure users from the wheel group can use sudo
  lineinfile:
    dest: /etc/sudoers.d/wheel
    state: present
    create: yes
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) ALL'
    validate: 'visudo -cf %s'
  tags:
    - el7
    - admin

- name: Set attributes of sudo configuration file for wheel group
  file:
    path: /etc/sudoers.d/wheel
    owner: root
    group: root
    mode: 0440
  tags:
    - el7
    - admin

- name: Set up SSH key for admin user
  authorized_key:
    user: "{{ el7_admin_user }}"
    key: "{{ el7_admin_ssh_key }}"
  when: el7_admin_user is defined
  tags:
    - el7
    - admin

