# roles/el7/tasks/security.yml
#
# Basic security settings
---
- name: Make sure SELinux is Enforcing
  selinux:
    policy: targeted
    state: "{{ el7_selinux_state }}"
  tags:
    - el7
    - security

- name: Make sure the firewall is running
  service:
    name: firewalld
    state: started
    enabled: yes
  tags:
    - el7
    - security

- name: Make sure basic services can pass through firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items:
    - dhcpv6-client
    - ssh
  notify:
    - restart firewalld
  tags:
    - el7
    - security

- name: Make sure user specified services can pass through firewall
  firewalld:
    service: "{{ item }}"
    permanent: true
    state: enabled
  with_items: el7_firewall_allow_services
  when: el7_firewall_allow_services is defined
  notify:
    - restart firewalld
  tags:
    - el7
    - security

- name: Make sure basic services can pass through firewall
  firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  with_items: el7_firewall_allow_ports
  when: el7_firewall_allow_ports is defined
  notify:
    - restart firewalld
  tags:
    - el7
    - security

