# roles/el7/tasks/users.yml
#
# Create groups and users on the system
---
- name: Add groups
  group:
    name: "{{ item }}"
    state: present
  with_items: el7_user_groups
  when: el7_user_groups is defined
  tags:
    - el7
    - users

- name: Add users
  user:
    name: "{{ item.name }}"
    state: present
    comment: "{{ item.comment }}"
    shell: "{{ item.shell|default('/bin/bash') }}"
    createhome: yes
    groups: "{{ ','.join(item.groups) }}"
    password: "{{ item.password }}"
  with_items: el7_users
  when: el7_users is defined
  tags:
    - el7
    - users

