# roles/ROLENAME/tasks/main.yml
---

# Download en unzip Siege en zet hem in de Home directory van de vagrant host.
#- name: Download Siege
#  get_url: url=http://download.joedog.org/siege/siege-3.1.0.tar.gz dest=/home/vagrant/ mode=0777
# unzippen

- name: copy siege tar
  copy:
    src: siege-3.1.0.tar.gz
    dest: /home/vagrant
  tags: tarcopy

- unarchive: src=/home/vagrant/siege-3.1.0.tar.gz dest=/home/vagrant/ copy=no

- name: install the 'Development tools' package group
  yum: name="@Development tools" state=present

- name: Configure and complete the installation process
  command: sudo {{ item }} chdir="/home/vagrant/siege-3.1.0"
  with_items:
    - ./configure
    - make
    - make install
    
- name: copy .siegerc
  copy:
    src: .siegerc
    dest: /home/vagrant
  tags: siege

- name: Make var-directory
  file: path=/usr/local/var state=directory mode=0777

- name: Make siegelog-file 
  file: path=/usr/local/var/siege.log state=touch mode=0777
  tags: siege

- name: copy yomoni tar
  copy:
    src: Yomoni.tar.gz
    dest: /home/vagrant
  tags: siege

- unarchive: src=/home/vagrant/Yomoni.tar.gz dest=/home/vagrant copy=no

- name: copy targets
  template: 
    src: urls.txt
    dest: /usr/local/etc/
  tags: siege

- name: extracting website tar to /var/www/html
  copy:
    src: Website.tar.gz
    dest: /var/www/html/
  tags: siege

- unarchive: src=/var/www/html/Website.tar.gz dest=/var/www/html/ copy=no

- name: setting permissions
  command: sudo chmod -R 777 /var/www/html

- name: cleaning up yomoni-tar
  command: sudo rm /home/vagrant/Yomoni.tar.gz

- name: cleaning up siege-tar
  command: sudo rm /home/vagrant/siege-3.1.0.tar.gz

- name: cleaning up html-folder
  command: sudo rm /var/www/html/Website.tar.gz


